apiVersion: v1
kind: Pod
metadata:
  name: log-app
  labels:
    app: log-app
spec:
  containers:
  - name: log-app
    image: quay.io/leahnp/leah_log_app:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: log-storage
      mountPath: /var/log
  - name: sidecar-log-collector
    image: dmalhot1/deepak-fluent:latest
    volumeMounts:
    - name: log-storage
      readOnly: true
      mountPath: /mnt/log
  volumes:
  - name: log-storage
    emptyDir: {}